name: Deployment Nest JS to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Docker Image
        run: docker build -t strategic/nixathon-nest .

      - name: Publish image to Docker Hub
        run: docker push strategic/nixathon-nest:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from Docker Hub
        run: docker pull strategic/nixathon-nest:latest

      - name: Delete Old Container
        run: docker rm -f nest-app

      - name: Run Docker Container
        run: docker run -d -p 3000:3000 --name nest-app strategic/nixathon-nest
